# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	
  # jboss webserver
  config.vm.define "webserver" do |webserver|

    webserver.vm.hostname = "webserver-jboss"

    webserver.vm.box = "hashicorp/precise32"

    webserver.vm.network "forwarded_port", guest: 8080, host: 8080

    webserver.vm.network "private_network", ip: "192.168.200.31"

	webserver.vm.provision "shell", inline: "echo 'hello world'"
   

  end
  # End jboss webserver
  
  # Database 
  config.vm.define "databaseServer" do |databaseServer|

    databaseServer.vm.hostname = "db-server"

    databaseServer.vm.box = "hashicorp/precise32"

    databaseServer.vm.network "forwarded_port", guest: 1521, host: 1521

    databaseServer.vm.network "private_network", ip: "192.168.200.32"

	databaseServer.vm.provision "shell", inline: "echo 'hello world'"
   

  end
  # End database
  
end
