# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	
	
	# Ansible host
  config.vm.define "ansibleHost" do |ansibleHost|

    ansibleHost.vm.hostname = "ansible.host"
    ansibleHost.vm.box = "hashicorp/precise32"
    ansibleHost.vm.network "private_network", ip: "192.168.200.30"
	ansibleHost.vm.synced_folder "../shared-ansible-confs", "/etc/ansible/"

    ansibleHost.vm.provider "virtualbox" do |v|
        v.customize [ "modifyvm", :id, "--cpus", "1" ]
        v.customize [ "modifyvm", :id, "--memory", "600" ]
    end
    
    ansibleHost.vm.provision "shell", path: "installAnsible.sh"

  end
  # End Ansible

end
